### ISSUE TITLE
README Images

### ISSUE THREAD

**Issue by jcmnn** [LibreTuner/LibreTuner#1]
This issue is for uploading images for use in the README without cluttering the main branch.

![main](https://user-images.githubusercontent.com/3116133/52010479-9b94cc00-24a3-11e9-904a-0d64776f6b6c.png)

![2dtable](https://user-images.githubusercontent.com/3116133/52010505-b404e680-24a3-11e9-8857-2d313a329fe2.png)

![image](https://user-images.githubusercontent.com/3116133/62159853-ab6d5b80-b2e0-11e9-931d-1b15481e83fb.png)

**Comment by IeDesprog** [comment]
do you have an email for contact ? I got something for you !
